### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/baby/user_graph_dict.npy

### ISSUE THREAD

**Issue by zhongshsh** [enoche/MMRec#5]
I run the code:

```
python main.py --model DualGNN --dataset baby
```

and get the error: 
```
 INFO =========1/25: Parameters:['aggr_mode', 'learning_rate', 'reg_weight', 'seed']=('add', 0.1, 0.1, 999)=======
Traceback (most recent call last):
  File "/data3/xx/workspacebb/MMRec/src/main.py", line 27, in <module>
    quick_start(model=args.model, dataset=args.dataset, config_dict=config_dict, save_model=True)
  File "/data3/xx/workspacebb/MMRec/src/utils/quick_start.py", line 74, in quick_start
    model = get_model(config['model'])(config, train_data).to(config['device'])
  File "/data3/xx/workspacebb/MMRec/src/models/dualgnn.py", line 53, in __init__
    self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']), allow_pickle=True).item()
  File "/data3/xx/workspacebb/miniconda3/lib/python3.10/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/baby/user_graph_dict.npy

```

**Comment by zhongshsh** [comment]
https://github.com/enoche/MMRec/issues/1
